import { chromium } from "playwright-core";
import { startServers } from "./server.mjs";
const servers = await startServers();
const browser = await chromium.launch({ executablePath: "/usr/bin/google-chrome-stable", headless: true });
const page = await browser.newPage();
page.on("console", (m) => { const t = m.text(); if (/Error|sapphire/.test(t) && !/Failed to load/.test(t)) console.log("[c]", t.slice(0, 200)); });
page.on("pageerror", (e) => console.log("[pageerror]", e.message.slice(0, 160), String(e.stack).split("\n").slice(1, 3).join("|").slice(0, 260)));
await page.goto(servers.hostUrl + "?blank");
await page.evaluate(() => window.harness.ready);
const id = await page.evaluate((u) => window.harness.installFromUrl(u), servers.siteUrl + "crx/ublite.crx");
await page.waitForTimeout(5000);
await page.reload();
await page.evaluate(() => window.harness.ready);
console.log("after reload ctxs:", await page.evaluate(() => JSON.stringify([...window.harness.sapphire.registry.contexts].map((c) => c.kind + ":" + c.alive))));
await page.waitForTimeout(6000);
console.log("after wait ctxs:", await page.evaluate(() => JSON.stringify([...window.harness.sapphire.registry.contexts].map((c) => c.kind + ":" + c.alive))));
const t = await page.evaluate((u) => window.harness.openTab(u), servers.siteUrl + "index.html");
await page.waitForTimeout(3000);
await page.evaluate(([id, t]) => window.harness.sapphire.clickAction(id, t), [id, t]);
await page.waitForTimeout(7000);
console.log("popup", await page.evaluate(() => { const w = window.harness.popupWindow(); const d = w.document; return JSON.stringify({ text: d.body.innerText.slice(0, 60), chrome: Object.keys(w.chrome || {}) }); }));
await browser.close(); await servers.close();
